### PR TITLE
#1 warm up

### PR DESCRIPTION
**Pull request by KrishayNair**
issue: #1 
added Name and github id.
image

### CODE REVIEW

**Comment by muffinboy19** [comment]
pls follow the pr template @KrishayNair

**Comment by KrishayNair** [comment]
> pls follow the pr template @KrishayNair
what ?

**Comment by KrishayNair** [comment]
> pls follow the pr template @KrishayNair

like what change should i do ?

**Comment by insanecoder02** [comment]
> > pls follow the pr template @KrishayNair
> 
> like what change should i do ?

folow the template given in PR_TEMPLATE.md for creating pull request

**Comment by KrishayNair** [comment]
Added Name and github id

**Comment by KrishayNair** [comment]
now is it fine ?

**Comment by KrishayNair** [comment]
please check @muffinboy19  @insanecoder02

**Pull request merged**
