### PR TITLE
add name and github account to contributors.xml

### PR DESCRIPTION
**Pull request by optimus-pride**

### CODE REVIEW

**Comment by insanecoder02** [comment]
please follow the pr template and make sure your pr has no merge conflicts

**Comment by insanecoder02** [comment]
send a new PR for the issue with correct PR template and no merge conflicts

**Comment by optimus-pride** [comment]
> send a new PR for the issue with correct PR template and no merge conflicts

hey, it says PR closed now, so do i send a new PR ?

**Comment by optimus-pride** [comment]
> > send a new PR for the issue with correct PR template and no merge conflicts
> 
> hey, it says PR closed now, so do i send a new PR ?

i've sent a new PR with correct template

**Pull request closed without merging**
